services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6543:6543"
    environment:
      - BACKEND_SECRET_KEY=${BACKEND_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./alarm_alert/migrations:/app/alarm_alert/migrations
      - ./analysis_reporting/migrations:/app/analysis_reporting/migrations
      - ./communication/migrations:/app/communication/migrations
      - ./data_acquisition/migrations:/app/data_acquisition/migrations
      - ./forecasting/migrations:/app/forecasting/migrations
      - ./optimization_control/migrations:/app/optimization_control/migrations
      - ./security/migrations:/app/security/migrations
      - ./simulation/migrations:/app/simulation/migrations
      - ./media:/app/media
    depends_on:
      db_v17:
        condition: service_healthy

  db_v17:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_v17_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_v17_data: